export let dummyWindowsAndTabs = [
  {
    alwaysOnTop: false,
    focused: false,
    height: 1416,
    id: 1,
    incognito: false,
    left: 1912,
    state: "maximized",
    tabs: [
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://s.yimg.com/rz/l/favicon.ico",
        height: 1281,
        highlighted: false,
        id: 2,
        incognito: false,
        index: 0,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Yahoo",
        url: "about:blank",
        width: 2560,
        windowId: 1,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl:
          "chrome-extension://iofccfgjcakiohdkbplbcajjfedlkjkg/favicon.ico",
        height: 1329,
        highlighted: false,
        id: 13,
        incognito: false,
        index: 1,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "React App",
        url:
          "chrome-extension://iofccfgjcakiohdkbplbcajjfedlkjkg/index.html#manage",
        width: 2560,
        windowId: 1,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "",
        height: 1329,
        highlighted: false,
        id: 17,
        incognito: false,
        index: 2,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Extensions",
        url: "chrome://extensions/",
        width: 2560,
        windowId: 1,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl:
          "https://www.idg.se/polopoly_fs/2.109.1584700971!/favicon.ico",
        height: 1297,
        highlighted: false,
        id: 20,
        incognito: false,
        index: 3,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "IDG.se - Störst på it-nyheter",
        url: "https://www.idg.se/",
        width: 2560,
        windowId: 1,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://kraken.ignimgs.com/static/favicon.ico",
        height: 1329,
        highlighted: false,
        id: 22,
        incognito: false,
        index: 4,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Video Game News, Reviews, and Walkthroughs - IGN",
        url: "https://www.ign.com/",
        width: 2560,
        windowId: 1,
      },
      {
        active: true,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://static.xx.fbcdn.net/rsrc.php/yo/r/iRmz9lCMBD2.ico",
        height: 1329,
        highlighted: true,
        id: 24,
        incognito: false,
        index: 5,
        mutedInfo: {
          muted: false,
        },
        openerTabId: 22,
        pinned: false,
        selected: true,
        status: "complete",
        title: "Facebook – log in or sign up",
        url: "https://www.facebook.com/",
        width: 2560,
        windowId: 1,
      },
    ],
    top: -8,
    type: "normal",
    width: 2576,
  },
  {
    alwaysOnTop: false,
    focused: false,
    height: 1416,
    id: 2,
    incognito: false,
    left: 1912,
    state: "maximized",
    tabs: [
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://s.yimg.com/rz/l/favicon.ico",
        height: 1281,
        highlighted: false,
        id: 212,
        incognito: false,
        index: 0,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Yahoo",
        url: "about:blank",
        width: 2560,
        windowId: 2,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl:
          "chrome-extension://iofccfgjcakiohdkbplbcajjfedlkjkg/favicon.ico",
        height: 1329,
        highlighted: false,
        id: 1312,
        incognito: false,
        index: 1,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "React App",
        url: "about:blank",
        width: 2560,
        windowId: 2,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "",
        height: 1329,
        highlighted: false,
        id: 1712,
        incognito: false,
        index: 2,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Extensions",
        url: "about:blank",
        width: 2560,
        windowId: 2,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl:
          "https://www.idg.se/polopoly_fs/2.109.1584700971!/favicon.ico",
        height: 1297,
        highlighted: false,
        id: 2012,
        incognito: false,
        index: 3,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "IDG.se - Störst på it-nyheter",
        url: "about:blank",
        width: 2560,
        windowId: 2,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://kraken.ignimgs.com/static/favicon.ico",
        height: 1329,
        highlighted: false,
        id: 2212,
        incognito: false,
        index: 4,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Video Game News, Reviews, and Walkthroughs - IGN",
        url: "about:blank",
        width: 2560,
        windowId: 2,
      },
      {
        active: true,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://static.xx.fbcdn.net/rsrc.php/yo/r/iRmz9lCMBD2.ico",
        height: 1329,
        highlighted: true,
        id: 2412,
        incognito: false,
        index: 5,
        mutedInfo: {
          muted: false,
        },
        openerTabId: 22,
        pinned: false,
        selected: true,
        status: "complete",
        title: "Facebook – log in or sign up",
        url: "about:blank",
        width: 2560,
        windowId: 2,
      },
    ],
    top: -8,
    type: "normal",
    width: 2576,
  },
];

export let dummyTabGroups = [
  {
    groupId: "8kvgsvc8ydm",
    tabGroupCloseAll: false,
    tabGroupCloseInactiveTabs: true,
    tabGroupDontAskAgain: true,
    tabGroupDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fringilla at sem sit amet molestie. Suspendisse congue dapibus sem, tempor bibendum neque volutpat eget.",
    tabGroupName: "Amur Tiger Windows",
    windowCollection: [
      {
        alwaysOnTop: false,
        focused: true,
        height: 1416,
        id: 1,
        incognito: false,
        left: 1912,
        state: "maximized",
        tabs: [
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl: "https://s.yimg.com/rz/l/favicon.ico",
            height: 1281,
            highlighted: false,
            id: 2,
            incognito: false,
            index: 0,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "complete",
            title: "Yahoo",
            url:
              "https://www.yahoo.com/?fr=fpc-comodo&type=81_25050030006_77.0.3865.120_u_hp_sp",
            width: 2560,
            windowId: 1,
          },
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl:
              "chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/extension-icon64.png",
            height: 1329,
            highlighted: false,
            id: 8,
            incognito: false,
            index: 1,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "complete",
            title: "OneTab",
            url:
              "chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/onetab.html",
            width: 2560,
            windowId: 1,
          },
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl: "",
            height: 1329,
            highlighted: false,
            id: 9,
            incognito: false,
            index: 2,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "complete",
            title: "Extensions - Tabeon",
            url: "chrome://extensions/?id=iofccfgjcakiohdkbplbcajjfedlkjkg",
            width: 2560,
            windowId: 1,
          },
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            height: 1297,
            highlighted: false,
            id: 15,
            incognito: false,
            index: 3,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "complete",
            title: "New Tab",
            url: "chrome://newtab/",
            width: 2560,
            windowId: 1,
          },
          {
            active: true,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl:
              "chrome-extension://iofccfgjcakiohdkbplbcajjfedlkjkg/favicon.ico",
            height: 1329,
            highlighted: true,
            id: 16,
            incognito: false,
            index: 4,
            mutedInfo: {
              muted: false,
            },
            openerTabId: 9,
            pinned: false,
            selected: true,
            status: "complete",
            title: "React App",
            url:
              "chrome-extension://iofccfgjcakiohdkbplbcajjfedlkjkg/index.html#manage",
            width: 2560,
            windowId: 1,
          },
        ],
        top: -8,
        type: "normal",
        width: 2576,
      },
    ],
  },
  {
    groupId: "2awzzd6axrk",
    tabGroupCloseAll: false,
    tabGroupCloseInactiveTabs: true,
    tabGroupDontAskAgain: true,
    tabGroupDescription:
      "Aliquam et iaculis diam. Sed suscipit tincidunt dapibus. Ut maximus nisi ligula, vel tristique sapien mattis ac. Sed lectus neque, blandit id sapien eget",
    tabGroupName: "Data Science",
    windowCollection: [
      {
        alwaysOnTop: false,
        focused: true,
        height: 1416,
        id: 1,
        incognito: false,
        left: 1912,
        state: "maximized",
        tabs: [
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl: "https://s.yimg.com/rz/l/favicon.ico",
            height: 1281,
            highlighted: false,
            id: 2,
            incognito: false,
            index: 0,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "complete",
            title: "Yahoo",
            url:
              "https://www.yahoo.com/?fr=fpc-comodo&type=81_25050030006_77.0.3865.120_u_hp_sp",
            width: 2560,
            windowId: 1,
          },
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl:
              "chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/extension-icon64.png",
            height: 1329,
            highlighted: false,
            id: 8,
            incognito: false,
            index: 1,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "complete",
            title: "OneTab",
            url:
              "chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/onetab.html",
            width: 2560,
            windowId: 1,
          },
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl: "",
            height: 1329,
            highlighted: false,
            id: 9,
            incognito: false,
            index: 2,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "complete",
            title: "Extensions - Tabeon",
            url: "chrome://extensions/?id=iofccfgjcakiohdkbplbcajjfedlkjkg",
            width: 2560,
            windowId: 1,
          },
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            height: 1297,
            highlighted: false,
            id: 15,
            incognito: false,
            index: 3,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "complete",
            title: "New Tab",
            url: "chrome://newtab/",
            width: 2560,
            windowId: 1,
          },
          {
            active: true,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl:
              "chrome-extension://iofccfgjcakiohdkbplbcajjfedlkjkg/favicon.ico",
            height: 1329,
            highlighted: true,
            id: 16,
            incognito: false,
            index: 4,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: true,
            status: "complete",
            title: "React App",
            url:
              "chrome-extension://iofccfgjcakiohdkbplbcajjfedlkjkg/index.html#manage",
            width: 2560,
            windowId: 1,
          },
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl:
              "https://www.idg.se/polopoly_fs/2.109.1578906276!/favicon.ico",
            height: 1297,
            highlighted: false,
            id: 17,
            incognito: false,
            index: 5,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "loading",
            title: "IDG.se - Störst på it-nyheter",
            url: "https://www.idg.se/",
            width: 2560,
            windowId: 1,
          },
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl: "https://www.posti.fi/favicon.ico",
            height: 1329,
            highlighted: false,
            id: 18,
            incognito: false,
            index: 6,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "complete",
            title:
              "Postin palvelut henkilöasiakkaille - Lähetä tai vastaanota - Posti",
            url: "https://www.posti.fi/fi",
            width: 2560,
            windowId: 1,
          },
        ],
        top: -8,
        type: "normal",
        width: 2576,
      },
    ],
  },
  {
    groupId: "k7pehnhu4vm",
    tabGroupCloseAll: false,
    tabGroupCloseInactiveTabs: true,
    tabGroupDontAskAgain: true,
    tabGroupDescription:
      "Morbi in elementum sem. Aliquam a diam libero. Phasellus eget faucibus turpis, in gravida quam. Maecenas interdum eget nisi a ullamcorper. Praesent ut sodales risus, sit ",
    tabGroupName: "Playstation Gaming",
    windowCollection: [
      {
        alwaysOnTop: false,
        focused: true,
        height: 1416,
        id: 1,
        incognito: false,
        left: 1912,
        state: "maximized",
        tabs: [
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl: "https://s.yimg.com/rz/l/favicon.ico",
            height: 1281,
            highlighted: false,
            id: 2,
            incognito: false,
            index: 0,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "complete",
            title: "Yahoo",
            url:
              "https://www.yahoo.com/?fr=fpc-comodo&type=81_25050030006_77.0.3865.120_u_hp_sp",
            width: 2560,
            windowId: 1,
          },
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl:
              "chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/extension-icon64.png",
            height: 1329,
            highlighted: false,
            id: 8,
            incognito: false,
            index: 1,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "complete",
            title: "OneTab",
            url:
              "chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/onetab.html",
            width: 2560,
            windowId: 1,
          },
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl: "",
            height: 1329,
            highlighted: false,
            id: 9,
            incognito: false,
            index: 2,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "complete",
            title: "Extensions - Tabeon",
            url: "chrome://extensions/?id=iofccfgjcakiohdkbplbcajjfedlkjkg",
            width: 2560,
            windowId: 1,
          },
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl: "https://nordic.ign.com/s/ign/favicon.ico",
            height: 1329,
            highlighted: false,
            id: 15,
            incognito: false,
            index: 3,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "complete",
            title: "IGN Nordic",
            url: "https://nordic.ign.com/",
            width: 2560,
            windowId: 1,
          },
          {
            active: true,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl:
              "chrome-extension://iofccfgjcakiohdkbplbcajjfedlkjkg/favicon.ico",
            height: 1329,
            highlighted: true,
            id: 16,
            incognito: false,
            index: 4,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: true,
            status: "complete",
            title: "React App",
            url:
              "chrome-extension://iofccfgjcakiohdkbplbcajjfedlkjkg/index.html#manage",
            width: 2560,
            windowId: 1,
          },
          {
            active: false,
            audible: false,
            autoDiscardable: true,
            discarded: false,
            favIconUrl: "https://www.posti.fi/favicon.ico",
            height: 1329,
            highlighted: false,
            id: 18,
            incognito: false,
            index: 5,
            mutedInfo: {
              muted: false,
            },
            pinned: false,
            selected: false,
            status: "complete",
            title:
              "Postin palvelut henkilöasiakkaille - Lähetä tai vastaanota - Posti",
            url: "https://www.posti.fi/fi",
            width: 2560,
            windowId: 1,
          },
        ],
        top: -8,
        type: "normal",
        width: 2576,
      },
    ],
  },
];
